# Generated by Django 3.1.7 on 2021-03-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tip', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('published', models.BooleanField(default=False)),
                ('links', models.ManyToManyField(to='tweets.Link')),
            ],
        ),
    ]
